apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
        - name: translator
          image: chaim022/translator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: TOPIC_SUB
              value: "text-telegram"
            - name: TOPIC_PUB
              value: "text-telegram-translated"
            - name: ES_HOST
              value: "http://elasticsearch:9200"
            - name: INDEX_LOG
              value: "translator"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: translator
spec:
  selector:
    app: translator
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
