apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classifier
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
        - name: classifier
          image: shuki120/classifier:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: TOPIC_SUB
              value: "text-telegram-translated"
            - name: ES_HOST
              value: "http://elasticsearch:9200"
            - name: INDEX_LOG
              value: "classifier"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: classifier
spec:
  selector:
    app: classifier
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
