apiVersion: apps/v1
kind: Deployment
metadata:
  name: checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checker
  template:
    metadata:
      labels:
        app: checker
    spec:
      containers:
        - name: checker
          image: chaim022/checker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_ID
              valueFrom:
                secretKeyRef:
                  name: tele-news-secrets
                  key: api-id
            - name: API_HASH
              valueFrom:
                secretKeyRef:
                  name: tele-news-secrets
                  key: api-hash
            - name: TOPIC_SUB
              value: "text-telegram"
            - name: ES_HOST
              value: "http://elasticsearch:9200"
            - name: INDEX_LOG
              value: "checker"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: checker
spec:
  selector:
    app: checker
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
